config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :openings
  resources :applicants
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  has_many :openings_applicants
  has_many :openings, through: :openings_applicants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/opening.rb
class Opening < ActiveRecord::Base
  has_many :openings_applicants
  has_many :applicants, through: :openings_applicants
end

app/models/openings_applicant.rb
class OpeningsApplicant < ActiveRecord::Base
  belongs_to :opening
  belongs_to :applicant
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  def index
    @applicants = Applicant.all

    render json: @applicants
  end

  def show
    @applicant = Applicant.find(params[:id])

    render json: @applicant
  end

  def destroy
    @applicant = Applicant.find(params[:id])
    @applicant.destroy
    render json: {success: true}  # AM: Nice.
  end

  def create
    @applicant = Applicant.create(applicant_params)
    render json: @applicant
  end

  def new   # AM: If you're using a front-end to generate a form, do you need this action?
    @applicant = Applicant.new
  end

  def edit  # AM: My previous comment applies here as well.
    @applicant = Applicant.find(params[:id])
  end

  def update
    @applicant = Applicant.find(params[:id])
    @applicant.update(applicant_params)
    render json: @applicant
  end

  private

  def applicant_params
    params.require(:applicant).permit(:name, :skills, :education, :years_exp)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/openings_controller.rb
class OpeningsController < ApplicationController
  def index
    @openings = Opening.all

    render json: @openings
  end

  def show
    @opening = Opening.find(params[:id])

    render json: @opening
  end

  def destroy
    @opening = Opening.find(params[:id])
    @opening.destroy
    render json: {success: true}
  end

  def create
    @opening = Opening.create(opening_params)
    render json: @opening
  end

  def new   # AM: If you're using a front-end to generate a form, do you need this action?
    @opening = Opening.new
  end

  def edit  # AM: My previous comment applies here as well.
    @opening = Opening.find(params[:id])
  end

  def update
    @opening = Opening.find(params[:id])
    @opening.update(opening_params)

    render json: @opening
  end

  private

  def opening_params
    params.require(:opening).permit(:opening_name, :skills, :education, :years_exp)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applicants/_form.html.erb
<!-- AM: Do you need all these Rails views if you're rendering everything in the browser using Angular? -->

<%= form_for @applicant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :skills %>
  <%= f.text_field :skills%>

  <%= f.label :education %>
  <%= f.text_field :education %>

  <%= f.label :years_experience %>
  <%= f.number_field :years_exp %>

  <%= f.submit %>
<% end %>

app/views/applicants/edit.html.erb
<h1>Edit Applicant</h1>

<%= render 'form' %>

<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<nav>
  <ul>
    <li><%= link_to "Back to Home", root_path %></li>
  </ul>
</nav>
<h1>All Applicants</h1>
<%= link_to "new applicant", new_applicant_path %>
<ul>
  <% @applicants.each do |applicant| %>
  <li><%= link_to applicant.name, applicant %>,</li>
  <li><%= applicant.skills %>,</li>
  <li><%= applicant.education %>,</li>
  <li><%= applicant.years_exp %></li>
  <li>
    <ul>
      <li><%= link_to "Edit", edit_applicant_path(applicant) %></li>
      <li><%= link_to "Delete", applicant_path(applicant), method: :delete %></li>
    </ul>
  </li>
  <% end %>
</ul>

app/views/applicants/new.html.erb
<h1>New Applicant</h1>

<%= render 'form' %>

<%= link_to 'Back', applicants_path %>

app/views/applicants/show.html.erb
<nav>
  <ul>
    <li><%= link_to "Back to All Applicants", applicants_path %></li>
  </ul>
</nav>

<h1><%= @applicant.name %></h1>
<ul>
  <li><%= @applicant.skills %></li>
  <li><%= @applicant.education %></li>
  <li><%= @applicant.years_exp %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quali-Fi API</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/openings/_form.html.erb
<%= form_for @opening do |f| %>
  <%= f.label :name %>
  <%= f.text_field :opening_name %>

  <%= f.label :skills %>
  <%= f.text_field :skills%>

  <%= f.label :education %>
  <%= f.text_field :education %>

  <%= f.label :years_experience %>
  <%= f.number_field :years_exp %>

  <%= f.submit %>
<% end %>

app/views/openings/edit.html.erb
<h1>Edit Opening</h1>

<%= render 'form' %>

<%= link_to 'Back', openings_path %>

app/views/openings/index.html.erb
<nav>
  <ul>
    <li><%= link_to "Back to Home", root_path %></li>
  </ul>
</nav>
<h1>All Openings</h1>
<%= link_to "new opening", new_opening_path %>
<ul>
  <% @openings.each do |opening| %>
  <li><%= link_to opening.opening_name, opening %>,</li>
  <li><%= opening.skills %>,</li>
  <li><%= opening.education %>,</li>
  <li><%= opening.years_exp %></li>
  <li>
    <ul>
      <li><%= link_to "Edit", edit_opening_path(opening) %></li>
      <li><%= link_to "Delete", opening_path(opening), method: :delete %></li>
    </ul>
  </li>
  <% end %>
</ul>

app/views/openings/new.html.erb
<h1>New Opening</h1>

<%= render 'form' %>

<%= link_to 'Back', openings_path %>

app/views/openings/show.html.erb
<nav>
  <ul>
    <li><%= link_to "Back to All Openings", openings_path %></li>
  </ul>
</nav>

<h1><%= @opening.opening_name %></h1>
<ul>
  <li><%= @opening.skills %></li>
  <li><%= @opening.education %></li>
  <li><%= @opening.years_exp %></li>
</ul>

app/views/welcome/index.html.erb
<h1>Quali-Fi API</h1>
<p>Interested in <%= link_to "Openings", openings_path %> or <%= link_to "Applicants", applicants_path %>?</p>